option(CANDIA_BUILD_TESTS "Build the 'tests', which are effectively just a more exhaustive set of executables for testing the evolution." OFF)
if (CANDIA_BUILD_TESTS)
  add_subdirectory(main)
  add_subdirectory(plot-generation)
  if (CANDIA_WITH_LHAPDF)
	add_subdirectory(testing)
	add_subdirectory(lhapdf-datafile)
  endif()
endif()
