find_program(LHAPDF_CONFIG
  NAMES bin/lhapdf-config
  HINTS ${CANDIA_LHAPDF_DIR})
if (LHAPDF_CONFIG)
  execute_process(
    COMMAND ${LHAPDF_CONFIG} --incdir
    OUTPUT_VARIABLE LHAPDF_INCLUDE_DIR
    OUTPUT_STRIP_TRAILING_WHITESPACE
  )
  set(LHAPDF_INCLUDE_DIR ${LHAPDF_INCLUDE_DIR} CACHE STRING INTERNAL)

  execute_process(
    COMMAND ${LHAPDF_CONFIG} --libs
    OUTPUT_VARIABLE LHAPDF_LIBRARIES
    OUTPUT_STRIP_TRAILING_WHITESPACE
  )
  set(LHAPDF_LIBRARIES ${LHAPDF_LIBRARIES} CACHE STRING INTERNAL)

  execute_process(
    COMMAND ${LHAPDF_CONFIG} --version
    OUTPUT_VARIABLE LHAPDF_VERSION
    OUTPUT_STRIP_TRAILING_WHITESPACE
  )
  set(LHAPDF_VERSION ${LHAPDF_VERSION} CACHE STRING INTERNAL)

  include(FindPackageHandleStandardArgs)
  find_package_handle_standard_args(LHAPDF REQUIRED_VARS LHAPDF_INCLUDE_DIR LHAPDF_LIBRARIES VERSION_VAR LHAPDF_VERSION)  
endif(LHAPDF_CONFIG)
