find_program(LHAPDF_CONFIG
  NAMES bin/lhapdf-config
  HINTS ${CANDIA_LHAPDF_DIR})
if (LHAPDF_CONFIG)
  execute_process(
    COMMAND ${LHAPDF_CONFIG} --incdir
    OUTPUT_VARIABLE LHAPDF_INCLUDE_DIR
    ERROR_QUIET
    RESULT_VARIABLE LHAPDF_INCDIR_RESULT
    OUTPUT_STRIP_TRAILING_WHITESPACE
  )
  if (NOT ${LHAPDF_INCDIR_RESULT} EQUAL 0)
     execute_process(
      COMMAND ${LHAPDF_CONFIG} --includedir
      OUTPUT_VARIABLE LHAPDF_INCLUDE_DIR
      ERROR_QUIET
      RESULT_VARIABLE LHAPDF_INCLUDEDIR_RESULT
      OUTPUT_STRIP_TRAILING_WHITESPACE)
  endif()
  
  
  set(LHAPDF_INCLUDE_DIR ${LHAPDF_INCLUDE_DIR} CACHE STRING INTERNAL)

  execute_process(
    COMMAND ${LHAPDF_CONFIG} --libs
    OUTPUT_VARIABLE LHAPDF_LIBRARIES
    OUTPUT_STRIP_TRAILING_WHITESPACE
  )
  set(LHAPDF_LIBRARIES ${LHAPDF_LIBRARIES} CACHE STRING INTERNAL)

  execute_process(
    COMMAND ${LHAPDF_CONFIG} --version
    OUTPUT_VARIABLE LHAPDF_VERSION
    OUTPUT_STRIP_TRAILING_WHITESPACE
  )
  set(LHAPDF_VERSION ${LHAPDF_VERSION} CACHE STRING INTERNAL)

  include(FindPackageHandleStandardArgs)
  find_package_handle_standard_args(LHAPDF REQUIRED_VARS LHAPDF_INCLUDE_DIR LHAPDF_LIBRARIES VERSION_VAR LHAPDF_VERSION)  
endif(LHAPDF_CONFIG)
