option(CANDIA_BUILD_EXAMPLES "Build the examples" ON)
if (CANDIA_BUILD_EXAMPLES)
  add_executable(evolve_dglap evolve_dglap.cpp)
  target_include_directories(evolve_dglap PUBLIC ${CMAKE_SOURCE_DIR}/include)
  target_link_libraries(evolve_dglap PUBLIC candia)

  add_executable(lhapdf_grid lhapdf_grid.cpp)
  target_include_directories(lhapdf_grid PUBLIC ${CMAKE_SOURCE_DIR}/include)
  target_link_libraries(lhapdf_grid PUBLIC candia)
  file(COPY infofile.in DESTINATION ${CMAKE_CURRENT_BINARY_DIR})
endif()
